### PR TITLE
feat: graphql codegen queries

### PR DESCRIPTION
**Pull request by satwikrprabhu**
Queries for Accommodation Form & Dashboard

### CODE REVIEW

**Comment by jevil25** [comment]
### Changes:
1) Give some bottom spacing here in the request form
2) Isn't this form for users to fill during registration? 
3) Accommodation Request Table width you can increase
4) Also anyone can see this page you can maybe keep a check role is user, organizer....... then redirect to homepage

Screenshot (152)

**Comment by satwikrprabhu** [comment]
Yepp users have to fill it during registration. @SrivatsaRUpadhya added it here just for testing. 
Also we have a functionality that allows only Accommodation Commitee members, we'll implement it to all queries and mutations

**Comment by satwikrprabhu** [comment]
I'm working on adding hotel details option.

**Comment by satwikrprabhu** [comment]
> ### Changes:
> 1. Give some bottom spacing here in the request form
> 2. Isn't this form for users to fill during registration?
> 3. Accommodation Request Table width you can increase
> 4. Also anyone can see this page you can maybe keep a check role is user, organizer....... then redirect to homepage
> 5. what about add hotel details option or adding that manually in db?
> 
> Screenshot (152)

everthing mentioned here fixed

**Review by jevil25 — APPROVED** [review]

**Pull request merged**
